# Generated by Django 3.2.21 on 2023-10-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20231013_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(blank=True, default=None),
        ),
    ]
